# movie db svc
---
apiVersion: v1
kind: Service
metadata:
  name: movie_db
  labels:
    {{- include "jenkinsexam.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.db.type }}
  ports:
    - port: {{ .Values.service.db.port }}
      targetPort: 5432
      protocol: TCP
      name: http
  selector:
    {{- include "jenkinsexam.selectorLabels" . | nindent 4 }}
