apiVersion: v1
kind: Service
metadata:
  name: cast_service
spec:
  selector:
    app: {{ .Release.Name }}-castapp
  ports:
    - protocol: TCP
      port: {{ .Values.service.app.port }}
      targetPort: {{ .Values.service.app.port }}