apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-castapp
  labels:
    app: {{ .Release.Name }}-castapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    app: {{ .Release.Name }}-castapp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-castapp
    spec:
      containers:
        - name: {{ .Release.Name }}-castapp
          image: "{{ .Values.image.cast.repository }}:{{ .Values.image.cast.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.app.port }}
              protocol: TCP