apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-moviedb
spec:
  selector:
    app: {{ .Release.Name }}-moviedb
  ports:
    - protocol: TCP
      port: {{ .Values.service.db.port }}
      targetPort: {{ .Values.service.db.port }}