apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-movieapp
spec:
  selector:
    app: {{ .Release.Name }}-movieapp
  ports:
    - protocol: TCP
      port: {{ .Values.service.app.port }}
      targetPort: {{ .Values.service.app.port }}