apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy
spec:
  selector:
    app: {{ .Release.Name }}-proxy
  ports:
    - protocol: TCP
      port: {{ .Values.service.proxy.port }}
      targetPort: {{ .Values.service.proxy.port }}